[package]
name = "rustic_ray"
version = "0.1.0"
authors = ["Guy"]
edition = "2018"

[[example]]
name = "animation"
path = "examples/animation/src/main.rs"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
rayon = "1.5.0"

[dev-dependencies]
clap = "3.0.0-beta.2"
image = "0.23.12"